### ISSUE TITLE
Web support

### ISSUE THREAD

**Issue by FiifiB** [duytq94/flutter-intro-slider#100]
This is really great library. Do you plan to add web support for this as well as null safety? Looking forward to that addition

**Comment by LautaroLobo12** [comment]
There's already a PR for migrating to null safety: #102

**Comment by duytq94** [comment]
Hi all,
https://github.com/duytq94/flutter-intro-slider/pull/102 has been merged

**Comment by duytq94** [comment]
Web support has almost done except this error `Unsupported operation: Platform._operatingSystem` because I'm using `Platform.isIOS` to detect platform to using appropriate `CupertinoScrollbar` (iOS devices) or `Scrollbar` (Android devices).
I can force only using one of them to pass this error but actually I would like to keep it for the best ux.
Is there any suggestion for this?
