### ISSUE TITLE
renderDoneBtn and other should't be default TextButton

### ISSUE THREAD

**Issue by Fintasys** [duytq94/flutter-intro-slider#111]
Hey ! 
Thanks for your hard work on this awesome library !

I've noticed that all buttons, even if you define your own widget, are default `TextButtons`. I think that's rather confusing and should be only the case if only `nameNextBtn` is set. Building the widget just as given would give us the chance to adjust the button for next and others like I'm trying to do.

Let me know what do you think. 
Thank you!

**Comment by duytq94** [comment]
Hi,
You're right, I haven't think about it when I starting, rendering entire your custom button is more flexible than wrapping it by `TextButton`.
I will update it later, if you could make a PR, I appreciate it

**Comment by Fintasys** [comment]
@duytq94 Thank you very much ! At the moment I can't find time for that, but I gonna keep it in mind and check again once I have more time 🙇

**Comment by duytq94** [comment]
I just updated (still using `TextButton`) but with more flexibility and clearly at here https://github.com/duytq94/flutter-intro-slider/releases/tag/3.0.0
The reason I'm still using `TextButton` for wrapping because:
- You can pass a child widget and ButtonStyle to TextButton, which I think you can custom almost all cases
- Render entire your custom widget without wrapping by `TextButton`, you hard to handle onPress action (eg: how to check slide is animating to prevent jump to next tab like photo below?)
![Screen Shot 2021-06-19 at 1 08 58 AM](https://user-images.githubusercontent.com/24253421/122601141-0eb23380-d09b-11eb-8156-76c17dea24b5.png)

**Comment by Fintasys** [comment]
@duytq94 Thanks for looking into this issue and this improvement which is already very helpful !

To answer your question, something like this would be possible I guess
```
GestureDetector(
    onTap: () {
        // Logic 
    },
    child: IgnorePointer(
        child: renderCustomWidget,
    )
)
```

**Comment by duytq94** [comment]
OK, I'll close this issue since the latest improvement has given users to custom almost cases, thanks.
