### ISSUE TITLE
Function to move to next page

### ISSUE THREAD

**Issue by Daanchaam** [duytq94/flutter-intro-slider#34]
First of all, great plugin! I've been using it in multiple apps and have been experimenting with routing to several other widgets from this one, as well as moving back to this plugin to implement for instance a registration. However, I encountered a problem when moving back to the plugin, since I wanted to move to the next page upon completing an action (i.e. upon `Navigator.of(context).pop(true) ) `

- Problem: At the moment it is only possible to move to the next page by clicking the next button. Where this can be styled, it can not be edited to be another widget such as the center widget. To call the tabcontroller from the IntroSlider Widget is possible, yet very cumbersome. 

- Proposal: Create an (optional) function (e.g. moveForward, moveBackward) to move to the next or previous page. This can be implemented using the tabcontroller as it is done now in buildNextButton() (line 765)

**Comment by duytq94** [comment]
Hi @Daanchaam 

- I plan to add another function named `goToTab(index)` so the user can go to any tab index they need.

- But I stuck in a problem: How to pass data from child widget to its parent (pass data up with widgets).

- Because as normal, the child will receive data and function from the parent, now if we would like to do this feature, we have to find another way to do the opposite.

- I made it worked, but my way is not the orthodox way. Do you have any idea?

**Comment by Daanchaam** [comment]
Unfortunately, passing data to a parent widget is not possible in flutter. The first thing that comes to mind is setting a global variable (https://api.flutter.dev/flutter/widgets/GlobalKey-class.html) which gets refreshed by the child widget. Here, a listener should be built in, but I don’t have details on this. 
This stackoverflow article might help: https://stackoverflow.com/questions/51463906/emit-the-data-to-parent-widget-in-flutter

**Comment by duytq94** [comment]
I have another way to solve it, maybe it's strange, but it doesn't break the Dart term.
Please checkout the lastest version (2.2.2).
Details at here fa4de022b941c77e5530cd2c7387312e9dd96934
Keep feel free to discussing.

**Comment by Daanchaam** [comment]
Works like a charm! Thanks for the implementation.
