### ISSUE TITLE
if i want to router another page after the slider done, how to do?

### ISSUE THREAD

**Issue by sixinyiyu** [duytq94/flutter-intro-slider#4]
void onDonePress() {
    Navigator.pushAndRemoveUntil(
      context, new MaterialPageRoute(
      builder: (context) => new HomeView(),), 
      (route) => route == null
    );

**Comment by duytq94** [comment]
I got it, let's me check at weekend, thanks.

**Comment by j3g** [comment]
why did you close ticket? the example does not show a "Navigator.push"

**Comment by duytq94** [comment]
Hi @j3g 
At that time, I just fix the example (the previous example won't navigate since I use the wrong Widget) but not add the detail code how to navigate since I have to add another dart file like home.dart to demo, and when I import this file from intro.dart to navigate from here, the dartpub will warn me when I publish the plugin like this:
https://github.com/dart-lang/sdk/issues/31563
Anyway, I added the navigate code in example but comment it to avoid this warning
