### ISSUE TITLE
i want to add text in bottom of screen after slider ends how can i add?

### ISSUE THREAD

**Issue by urvashikharecha** [duytq94/flutter-intro-slider#56]
i have slider like this
  ```
IntroSlider(
    slides: this.slides,
      colorSkipBtn: Color(0xfffccd01),
      colorDoneBtn: Color(0xfffccd01),
      colorActiveDot: Color(0xfffccd01),
      sizeDot: 10.0,
      isShowSkipBtn : false,
      onDonePress: this.onDonePress,
      onSkipPress: this.onSkipPress,
    ),
```
i tried this but not working
```
Column(children: <Widget>[
    IntroSlider(
    slides: this.slides,
      colorSkipBtn: Color(0xfffccd01),
      colorDoneBtn: Color(0xfffccd01),
      colorActiveDot: Color(0xfffccd01),
      sizeDot: 10.0,
      isShowSkipBtn : false,
      onDonePress: this.onDonePress,
      onSkipPress: this.onSkipPress,
    ),
      Text('ghfgh')
    ],),
```

**Comment by duytq94** [comment]
You have to wrap `IntroSlider` widget by some bounded widget because as default, `IntroSlider` tries to be as big as possible, but it was put inside another render object (`Column` in your case) that allows its children to pick their own size.
You can solve like this
```
return Column(
      children: <Widget>[
        Flexible(
          child: IntroSlider(...),
        ),
        Text('some of my words')
      ],
```
![Simulator Screen Shot - iPhone 11 Pro Max - 2019-12-21 at 10 21 40](https://user-images.githubusercontent.com/24253421/71302356-1a0c9c00-23dd-11ea-9b7a-c6ee5c3fbf1e.png)

**Comment by urvashikharecha** [comment]
i want to show dot indicator on left side and done button on right side so any help?
